name: com.whitelabel
base: core18
version: ''
summary: Demonstrates how to use the News module.
description: |
  Demonstrates how to use the News module.
confinement: devmode
grade: devel
apps:
  com.whitelabel:
    command: com.whitelabel
    desktop: local/com.whitelabel.desktop
parts:
  desktop:
    plugin: dump
    source: snap
  assets:
    plugin: dump
    source: assets
  app:
    plugin: dump
    source: build
    stage-packages:
      - libx11-6
      - libxrandr2
      - libxcursor1
      - libxinerama1
      - libglu1-mesa
      - libgcc1
      - libstdc++6
      - libtinfo5
      - zlib1g