version: '3'
services: 
    ion:
        container_name: ion
        build: 
            context: .
            dockerfile: Dockerfile-ion
        image: ion
        network_mode: "host"
        restart: on-failure
        depends_on: 
            - rabbit

    islb:
        container_name: islb
        build: 
            context: .
            dockerfile: Dockerfile-islb
        image: islb
        network_mode: "host"
        restart: on-failure
        depends_on: 
            - rabbit
            - redis

    rabbit:
        container_name: rabbit
        image: rabbitmq
        network_mode: "host"

    redis:
        container_name: redis
        image: redis
        network_mode: "host"
        